apiVersion: v1
kind: Service
metadata:
  name: sequencer-node-service
  namespace: test
spec:
  ports:
    - name: consensus
      port: 55540
      targetPort: 55540
    - name: http
      port: 8080
      targetPort: 8080
    - name: mempool
      port: 55542
      targetPort: 55542
    - name: monitoring
      port: 8082
      targetPort: 8082
    - name: state
      port: 55541
      targetPort: 55541
  selector:
    app: sequencer-node
  type: ClusterIP
