[package]
name = "papyrus_proc_macros"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Procedural macros for the Papyrus node"

[dependencies]
quote.workspace = true
syn = { workspace = true, features = ["full"] }
tracing.workspace = true

[dev-dependencies]
metrics.workspace = true
metrics-exporter-prometheus.workspace = true
papyrus_common.path = "../papyrus_common"
papyrus_test_utils.path = "../papyrus_test_utils"
prometheus-parse.workspace = true

[lib]
proc-macro = true

[lints]
workspace = true
