[package]
name = "papyrus_config"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "A library for handling node configuration."

[dependencies]
clap = { workspace = true, features = ["env", "string"] }
itertools.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["arbitrary_precision"] }
starknet_infra_utils.workspace = true
strum_macros.workspace = true
thiserror.workspace = true
tracing.workspace = true
validator = { workspace = true, features = ["derive"] }

[dev-dependencies]
assert_matches.workspace = true
itertools.workspace = true
lazy_static.workspace = true
papyrus_test_utils.path = "../papyrus_test_utils"
starknet_api.path = "../starknet_api"
starknet_infra_utils.path = "../starknet_infra_utils"
tempfile.workspace = true

[lints]
workspace = true
