name: Main-CI-Flow

on:
  push:
    branches:
      - main
      - main-v[0-9].**
    tags:
      - v[0-9].**

  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - auto_merge_enabled
      - edited

# On PR events, cancel existing CI runs on this same PR for this workflow.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install commitlint
        run: npm install --global @commitlint/cli @commitlint/config-conventional

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request' && !(contains(github.event.pull_request.title, 'merge-main') || contains(github.event.pull_request.title, 'merge main'))
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: commitlint --from "$BASE_SHA" --to "$HEAD_SHA" --verbose

      - name: Validate PR title with commitlint
        if: github.event_name != 'merge_group' && github.event_name != 'push' && !(contains(github.event.pull_request.title, 'merge-main') || contains(github.event.pull_request.title, 'merge main'))
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: echo "$TITLE" | commitlint --verbose

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master # TODO(Nimrod, 15/8/2024): Use stable toolchain.
        with:
          components: rustfmt
          toolchain: nightly-2024-04-29
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-rust-ubuntu-latest"
      - run: scripts/rust_fmt.sh --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      # Enviorment setup.
      - uses: actions/checkout@v4
      - uses: Noelware/setup-protoc@1.1.0
      - uses: baptiste0928/cargo-install@v3
        with:
          components: clippy

      - name: Set up Native Dependencies
        uses: ./.github/actions/setup-native-deps
        id: native-deps

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-rust-ubuntu-latest"

      # Setup pypy and link to the location expected by .cargo/config.toml.
      - uses: actions/setup-python@v5
        id: setup-pypy
        with:
          python-version: "pypy3.9"
      - run: ln -s '${{ steps.setup-pypy.outputs.python-path }}' /usr/local/bin/pypy3.9
      - env:
          LD_LIBRARY_PATH: ${{ steps.setup-pypy.outputs.pythonLocation }}/bin
        run: echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}" >> $GITHUB_ENV

      - run: scripts/clippy.sh

  doc:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install_rust
      - name: Set up Native Dependencies
        uses: ./.github/actions/setup-native-deps
        id: native-deps
      - uses: Swatinem/rust-cache@v2
      - uses: Noelware/setup-protoc@1.1.0
        with:
          version: ${{env.PROTOC_VERSION}}
      - run: cargo doc -p blockifier -r --document-private-items --no-deps

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch the entire history.
          fetch-depth: 0
      - uses: ./.github/actions/install_rust
      - name: Set up Native Dependencies
        uses: ./.github/actions/setup-native-deps
        id: native-deps
      - uses: Noelware/setup-protoc@1.1.0
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-rust-ubuntu-latest"

      # Setup pypy and link to the location expected by .cargo/config.toml.
      - uses: actions/setup-python@v5
        id: setup-pypy
        with:
          python-version: "pypy3.9"
      - run: ln -s '${{ steps.setup-pypy.outputs.python-path }}' /usr/local/bin/pypy3.9
      - env:
          LD_LIBRARY_PATH: ${{ env.Python3_ROOT_DIR }}/bin
        run: echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}" >> $GITHUB_ENV
      - name: "Run tests pull request"
        if: github.event_name == 'pull_request'
        run: |
          python3 -m venv ci
          ci/bin/pip install -r scripts/requirements.txt
          ci/bin/python scripts/run_tests.py --changes_only --commit_id ${{ github.event.pull_request.base.sha }}
        env:
          SEED: 0

      - name: "Run tests on push"
        if: github.event_name == 'push'
        # TODO: Better support for running tests on push.
        run: |
          python3 -m venv ci
          ci/bin/pip install -r scripts/requirements.txt
          ci/bin/python scripts/run_tests.py
        env:
          SEED: 0

  taplo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install_rust
      - uses: Swatinem/rust-cache@v2
      - uses: baptiste0928/cargo-install@v3
        with:
          crate: taplo-cli
          version: "0.9.0"
          locked: true
      - run: scripts/taplo.sh

  machete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Machete (detect unused dependencies)
        uses: bnjbvr/cargo-machete@main

  check:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install_rust
      - uses: Swatinem/rust-cache@v2
      - uses: Noelware/setup-protoc@1.1.0
        with:
          version: ${{env.PROTOC_VERSION}}
      - name: Set up Native Dependencies
        uses: ./.github/actions/setup-native-deps
        id: native-deps
      - run: cargo check -p blockifier -r --all-features
