name: Replay

on:
  push:
    branches: [main, replay]
  pull_request:

jobs:
  clippy:
    runs-on: ubuntu-latest
    env:
      MLIR_SYS_190_PREFIX: /usr/lib/llvm-19/
      LLVM_SYS_191_PREFIX: /usr/lib/llvm-19/
      TABLEGEN_190_PREFIX: /usr/lib/llvm-19/
      CAIRO_NATIVE_RUNTIME_LIBRARY: libcairo_native_runtime.a
    steps:
      - uses: actions/checkout@v4
        with:
          # required to clone native as a git submodule
          submodules: recursive
      - uses: dtolnay/rust-toolchain@1.82.0
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Add LLVM Debian repository
        uses: myci-actions/add-deb-repo@10
        with:
          repo: deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-19 main
          repo-name: llvm-repo
          keys-asc: https://apt.llvm.org/llvm-snapshot.gpg.key
      - name: Install lld
        run: sudo apt install lld
      - name: Install LLVM
        run: sudo apt-get install llvm-19 llvm-19-dev llvm-19-runtime clang-19 clang-tools-19 lld-19 libpolly-19-dev libmlir-19-dev mlir-19-tools
      - name: Run cargo clippy
        run: |
          cd crates/blockifier
          cargo clippy --all-targets --all-features --no-deps

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2023-10-19
          components: rustfmt
      - name: Run cargo fmt
        run:  cargo +nightly-2023-10-19 fmt --all -- --check
