name: Replay

on:
  push:
    branches:
      - main
      - main-v[0-9].**
  pull_request:

jobs:
  clippy:
    runs-on: ubuntu-latest
    env:
      MLIR_SYS_190_PREFIX: /usr/lib/llvm-20/
      LLVM_SYS_191_PREFIX: /usr/lib/llvm-20/
      TABLEGEN_190_PREFIX: /usr/lib/llvm-20/
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.86.0
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Add LLVM Debian repository
        uses: myci-actions/add-deb-repo@10
        with:
          repo: deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-20 main
          repo-name: llvm-repo
          keys-asc: https://apt.llvm.org/llvm-snapshot.gpg.key
      - name: Install lld
        run: sudo apt install lld
      - name: Install LLVM
        run: sudo apt-get install llvm-20 llvm-20-dev llvm-20-runtime clang-20 clang-tools-20 lld-20 libpolly-20-dev libmlir-20-dev mlir-20-tools
      - name: Run cargo clippy
        run: |
          cd crates/blockifier
          cargo clippy --all-targets --all-features --no-deps
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2023-10-20
          components: rustfmt
      - name: Run cargo fmt
        run:  cargo +nightly-2023-10-20 fmt --all -- --check
